display the data from the list to the screen
LongNg89/MP-blog4pp pull request #25
Opened 2022-01-06 02:32 UTC by dangducminh

2022-01-06 05:48 UTC, LongNg89 commented
bug gì mới được chứ
m ko chụp logcat à?

2022-01-06 05:55 UTC, dangducminh commented
ko đổ data từ list -> recyclerview được , dữ liệu đã được lấy và in ra logcat ở line 92 của MessageFragment.java

2022-01-06 05:56 UTC, dangducminh commented
> bug gì mới được chứ m ko chụp logcat à?

ko đổ data từ list -> recyclerview được , dữ liệu đã được lấy và in ra logcat ở line 92 của MessageFragment.java

2022-01-06 14:17 UTC, LongNg89 commented
> > bug gì mới được chứ m ko chụp logcat à?
> 
> ko đổ data từ list -> recyclerview được , dữ liệu đã được lấy và in ra logcat ở line 92 của MessageFragment.java

log như cái #20 này xem mới hiểu được chứ?

2022-01-07 03:31 UTC, Bunrealbo approved these changes

2022-01-07 06:21 UTC, LongNg89 requested changes
sửa các lỗi đã comment

2022-01-07 06:21 UTC, LongNg89 commented on app/src/main/AndroidManifest.xml
> +            android:exported="false" />
đổi thành `android:exported="true"`

2022-01-07 06:21 UTC, LongNg89 commented on app/src/main/AndroidManifest.xml
> +            android:exported="false" />
@dangducminh

2022-01-07 06:21 UTC, LongNg89 commented on app/src/main/java/com/longng/blog4pp/AccountSetupActivity.java
> +        update.put("/avartar/",downloadUri);
typo: ~~avartar~~ `avatar`

2022-01-07 06:21 UTC, LongNg89 commented on app/src/main/java/com/longng/blog4pp/adapters/UserMessAdapter.java
> +public class UserMessAdapter extends RecyclerView.Adapter<UserMessAdapter.ViewHolder> {
refractor to `UserMessageAdapter` for clarity

2022-01-07 06:21 UTC, LongNg89 commented on app/src/main/java/com/longng/blog4pp/databaseReference/DataBaseManager.java
> +public class DataBaseManager {
refractor to `DatabaseManager.java` for clarity

2022-01-07 06:21 UTC, LongNg89 commented on app/src/main/java/com/longng/blog4pp/models/UserModel.java
> +        this.avartar = avartar;
typo: ~~avartar~~ `avatar`

2022-01-07 06:21 UTC, LongNg89 commented on app/src/main/res/layout/item_message.xml
> +<?xml version="1.0" encoding="utf-8"?>
refractor to `message_list_item.xml` for clarify

2022-01-07 06:21 UTC, LongNg89 commented on app/src/main/res/layout/item_user_chat.xml
> +<?xml version="1.0" encoding="utf-8"?>
refractor to `chat_user_list_item.xml` for clarify

2022-01-07 06:27 UTC, LongNg89 requested changes
kiểm tra lỗi chính tả

2022-01-07 06:27 UTC, LongNg89 commented on app/src/main/java/com/longng/blog4pp/adapters/UserMessAdapter.java
> +        holder.imvAvartars.setImageResource(R.mipmap.ic_launcher);
typo: ~~avartar~~ avatar

2022-01-07 16:37 UTC, LongNg89 approved these changes
ok

2022-01-07 16:40 UTC, merged